import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import {
  compileDeploymentLocationImport,
  directoryTemplateCsv,
  normalizeRow,
  previewDeploymentLocationImport,
  templateForProduct,
} from "../lib/deploymentLocationsImport.ts";
import {
  derivePrimaryWorkspaceAction,
  deriveWorkspaceSetupSteps,
  workspaceHealth,
} from "../lib/workspace/customerAdminFoundation.ts";

test("directory import: architecture evolves deployment_locations instead of adding a parallel directory table", () => {
  const migration = readFileSync(new URL("../supabase/migrations/20260806010000_add_tenant_scoped_directory_imports.sql", import.meta.url), "utf8");
  assert.match(migration, /ALTER TABLE public\.deployment_locations ADD COLUMN IF NOT EXISTS client_id/);
  assert.match(migration, /ALTER TABLE public\.deployment_locations ADD COLUMN IF NOT EXISTS workspace_id/);
  assert.doesNotMatch(migration, /CREATE TABLE IF NOT EXISTS public\.workspace_directory_records/);
});

test("directory import: product-aware templates are generated by the shared importer", () => {
  assert.equal(templateForProduct("retail").directoryLabel, "Outlet Directory");
  assert.equal(templateForProduct("fleet").directoryLabel, "Vehicle Directory");
  assert.equal(templateForProduct("build").directoryLabel, "Property / Site Directory");
  assert.equal(templateForProduct("healthcare").directoryLabel, "Facility Directory");
  assert.match(directoryTemplateCsv("fleet"), /vehicle_id/);
  assert.match(directoryTemplateCsv("build"), /site_name/);
});

test("directory import: validation returns grouped errors, warnings and information", () => {
  const preview = previewDeploymentLocationImport([
    { state: "", outlet_name: "No State", address: "Somewhere", outlet_code: "A-1" },
    { state: "Lagos", outlet_name: "No Address", outlet_code: "A-2" },
    { state: "Lagos", outlet_name: "Bad Coordinate", address: "VI", latitude: "999", outlet_code: "A-3" },
  ], [], "retail");
  assert.equal(preview.errors.length, 2);
  assert.equal(preview.warnings.length, 1);
  assert.equal(preview.information.length, 1);
  assert.equal(preview.rowsToInsert.length, 1);
});

test("directory import: duplicate detection stays in DeployIQ Core importer", () => {
  const rows = [
    normalizeRow({ state: "Lagos", outlet_name: "Shop A", address: "1 Road", outlet_code: "001" }),
    normalizeRow({ state: "Lagos", outlet_name: "Shop A", address: "1 Road", outlet_code: "001" }),
  ].filter((row) => "data" in row).map((row) => row.data);
  const summary = compileDeploymentLocationImport(rows, []);
  assert.equal(summary.rowsToInsert.length, 1);
  assert.equal(summary.skippedExactDuplicates, 1);
});

test("directory import: preview reports imported skipped duplicates errors and warnings", () => {
  const preview = previewDeploymentLocationImport([
    { state: "Lagos", outlet_name: "Shop A", address: "1 Road", outlet_code: "001" },
    { state: "Lagos", outlet_name: "Shop A", address: "1 Road", outlet_code: "001" },
  ], [], "retail");
  assert.equal(preview.imported, 1);
  assert.equal(preview.skipped, 1);
  assert.ok(preview.duplicates >= 1);
  assert.equal(preview.errors.length, 0);
  assert.ok("warnings" in preview);
});

test("directory import: duplicate warnings identify name and outlet code collisions", () => {
  const preview = previewDeploymentLocationImport([
    { state: "Lagos", outlet_name: "Devine Venture'S", address: "1 Road", outlet_code: "236120" },
    { state: "Lagos", outlet_name: "Devine Venture'S", address: "2 Road", outlet_code: "236120" },
  ], [], "retail");
  assert.equal(preview.duplicates, 1);
  assert.equal(preview.rowsToInsert.length, 1);
  const duplicateWarnings = preview.warnings.filter((issue) => issue.field === "duplicate");
  assert.equal(duplicateWarnings.length, 1);
  assert.match(duplicateWarnings[0].message, /Row 3 duplicates Row 2\. Same Outlet Name \(Devine Venture'S\) and Outlet Code \(236120\)\. This row will not be imported\./);
  assert.equal(preview.previewRows.filter((row) => row.status === "duplicate").length, 1);
  assert.equal(preview.errors.length + preview.duplicates, 1);
});

test("directory import: warnings alone still allow ready rows", () => {
  const preview = previewDeploymentLocationImport([
    { state: "Lagos", outlet_name: "No Address", outlet_code: "A-2" },
  ], [], "retail");
  assert.equal(preview.errors.length, 0);
  assert.equal(preview.duplicates, 0);
  assert.equal(preview.warnings.length, 1);
  assert.equal(preview.rowsToInsert.length, 1);
});

test("directory import: Customer Admin APIs derive ownership from authenticated workspace context", () => {
  const service = readFileSync(new URL("../lib/workspace/directoryImport.ts", import.meta.url), "utf8");
  const commitRoute = readFileSync(new URL("../app/api/workspace/directory/commit/route.ts", import.meta.url), "utf8");
  assert.match(service, /resolveCustomerWorkspaceContext/);
  assert.match(service, /p_client_id: workspace\.clientId/);
  assert.match(service, /p_workspace_id: workspace\.clientId/);
  assert.match(service, /p_imported_by: workspace\.userId/);
  assert.doesNotMatch(commitRoute, /clientId|workspaceId|tenantId/);
});

test("directory import: commit is atomic through a SQL transaction function", () => {
  const migration = readFileSync(new URL("../supabase/migrations/20260806010000_add_tenant_scoped_directory_imports.sql", import.meta.url), "utf8");
  const service = readFileSync(new URL("../lib/workspace/directoryImport.ts", import.meta.url), "utf8");
  assert.match(migration, /CREATE OR REPLACE FUNCTION public\.commit_workspace_directory_import/);
  assert.match(migration, /INSERT INTO public\.workspace_directory_import_batches/);
  assert.match(migration, /INSERT INTO public\.deployment_locations/);
  assert.match(migration, /UPDATE public\.workspace_onboarding_checklist_items/);
  assert.match(service, /\.rpc\("commit_workspace_directory_import"/);
});

test("directory import: import history and error report are tenant scoped", () => {
  const service = readFileSync(new URL("../lib/workspace/directoryImport.ts", import.meta.url), "utf8");
  const reportRoute = readFileSync(new URL("../app/api/workspace/directory/error-report/route.ts", import.meta.url), "utf8");
  assert.match(service, /workspace_directory_import_batches/);
  assert.match(service, /\.eq\("client_id", workspace\.clientId\)/);
  assert.match(service, /\.eq\("product_key", workspace\.productKey\)/);
  assert.match(reportRoute, /getWorkspaceDirectoryDashboard/);
});

test("directory import: successful import updates workspace setup progress and health", () => {
  const steps = deriveWorkspaceSetupSteps({
    directoryUploaded: true,
    projectCount: 0,
    membershipCount: 1,
    approvalWorkflowConfigured: false,
    campaignCount: 0,
    deploymentStarted: false,
  }, "retail");
  assert.equal(steps[0].status, "Completed");
  assert.equal(derivePrimaryWorkspaceAction(steps).primaryCta, "Create Your First Project");
  assert.equal(workspaceHealth({
    directoryUploaded: true,
    projectCount: 0,
    membershipCount: 1,
    approvalWorkflowConfigured: false,
    campaignCount: 0,
    deploymentStarted: false,
  }).find((item) => item.label === "Directory Uploaded")?.state, "Completed");
});

test("directory import: Platform Admin legacy API remains separate from Customer Admin upload", () => {
  const platformRoute = readFileSync(new URL("../app/api/deployment-locations/route.ts", import.meta.url), "utf8");
  const workspacePreviewRoute = readFileSync(new URL("../app/api/workspace/directory/preview/route.ts", import.meta.url), "utf8");
  assert.match(platformRoute, /requireAdmin\(request\)/);
  assert.match(platformRoute, /compileDeploymentLocationImport/);
  assert.match(workspacePreviewRoute, /previewWorkspaceDirectoryImport/);
});

test("directory import hardening: same external_id in same tenant and product is rejected", () => {
  const migration = readFileSync(new URL("../supabase/migrations/20260806010000_add_tenant_scoped_directory_imports.sql", import.meta.url), "utf8");
  assert.match(migration, /CREATE UNIQUE INDEX IF NOT EXISTS deployment_locations_workspace_product_external_id_uidx/);
  assert.match(migration, /client_id,\s*\n\s*workspace_id,\s*\n\s*product_key,\s*\n\s*lower\(btrim\(external_id\)\)/);
});

test("directory import hardening: same external_id in different tenants or products is allowed by scope", () => {
  const migration = readFileSync(new URL("../supabase/migrations/20260806010000_add_tenant_scoped_directory_imports.sql", import.meta.url), "utf8");
  assert.match(migration, /deployment_locations_workspace_product_external_id_uidx/);
  assert.match(migration, /client_id,\s*\n\s*workspace_id,\s*\n\s*product_key/);
  assert.doesNotMatch(migration, /UNIQUE INDEX IF NOT EXISTS deployment_locations_product_external_id_uidx/);
  assert.doesNotMatch(migration, /UNIQUE INDEX IF NOT EXISTS deployment_locations_external_id_uidx/);
});

test("directory import hardening: blank external_id does not trigger false uniqueness", () => {
  const migration = readFileSync(new URL("../supabase/migrations/20260806010000_add_tenant_scoped_directory_imports.sql", import.meta.url), "utf8");
  assert.match(migration, /NULLIF\(btrim\(external_id\), ''\) IS NOT NULL/);
});

test("directory import hardening: no strict Retail outlet_code unique index is added", () => {
  const migration = readFileSync(new URL("../supabase/migrations/20260806010000_add_tenant_scoped_directory_imports.sql", import.meta.url), "utf8");
  assert.doesNotMatch(migration, /deployment_locations_retail_outlet_code_uidx/);
});

test("directory import hardening: duplicate commit key reuses the existing batch", () => {
  const migration = readFileSync(new URL("../supabase/migrations/20260806010000_add_tenant_scoped_directory_imports.sql", import.meta.url), "utf8");
  const service = readFileSync(new URL("../lib/workspace/directoryImport.ts", import.meta.url), "utf8");
  assert.match(migration, /ADD COLUMN IF NOT EXISTS idempotency_key text/);
  assert.match(migration, /workspace_directory_import_batches_idempotency_uidx/);
  assert.match(migration, /SELECT batch\.id[\s\S]*batch\.idempotency_key = v_idempotency_key[\s\S]*RETURN v_batch_id/);
  assert.match(service, /p_idempotency_key: sourceFileHash/);
});

test("directory import hardening: batch row tenant and product mismatches are rejected", () => {
  const migration = readFileSync(new URL("../supabase/migrations/20260806010000_add_tenant_scoped_directory_imports.sql", import.meta.url), "utf8");
  assert.match(migration, /workspace_directory_import_batches_batch_scope_uidx/);
  assert.match(migration, /deployment_locations_import_batch_scope_fkey/);
  assert.match(migration, /FOREIGN KEY \(import_batch_id, client_id, workspace_id, product_key\)/);
  assert.match(migration, /REFERENCES public\.workspace_directory_import_batches\(id, client_id, workspace_id, product_key\)/);
});

test("directory import hardening: legacy null-tenant rows remain valid", () => {
  const migration = readFileSync(new URL("../supabase/migrations/20260806010000_add_tenant_scoped_directory_imports.sql", import.meta.url), "utf8");
  assert.match(migration, /\(client_id IS NULL AND workspace_id IS NULL\)\s*\n\s*OR client_id = workspace_id/);
  assert.match(migration, /WHERE client_id IS NOT NULL[\s\S]*workspace_id IS NOT NULL/);
});

test("directory import hardening: direct authenticated execution of the function is denied", () => {
  const migration = readFileSync(new URL("../supabase/migrations/20260806010000_add_tenant_scoped_directory_imports.sql", import.meta.url), "utf8");
  assert.match(migration, /REVOKE ALL ON FUNCTION public\.commit_workspace_directory_import/);
  assert.match(migration, /FROM anon/);
  assert.match(migration, /FROM authenticated/);
  assert.match(migration, /GRANT EXECUTE ON FUNCTION public\.commit_workspace_directory_import[\s\S]*TO service_role/);
});

test("directory import hardening: exact upload_directory checklist item is completed and unrelated items are unchanged", () => {
  const migration = readFileSync(new URL("../supabase/migrations/20260806010000_add_tenant_scoped_directory_imports.sql", import.meta.url), "utf8");
  assert.match(migration, /item\.item_key = 'upload_directory'/);
  assert.doesNotMatch(migration, /item\.item_key ILIKE/);
  assert.doesNotMatch(migration, /item\.label ILIKE/);
});

test("directory import workflow: discard and start-new actions are visible at the correct lifecycle points", () => {
  const client = readFileSync(new URL("../components/workspace/DirectoryImportClient.tsx", import.meta.url), "utf8");
  assert.match(client, /type ImporterState = "idle" \| "parsing" \| "validating" \| "preview_ready" \| "committing" \| "committed" \| "error"/);
  assert.match(client, /hasUncommittedPreview/);
  assert.match(client, /Discard Import/);
  assert.match(client, /importerState === "committed"/);
  assert.match(client, /Start New Import/);
  assert.match(client, /aria-disabled=\{!canCommit\}/);
});

test("directory import workflow: discard confirmation is keyboard accessible", () => {
  const client = readFileSync(new URL("../components/workspace/DirectoryImportClient.tsx", import.meta.url), "utf8");
  assert.match(client, /Discard this import\?/);
  assert.match(client, /The uploaded file, preview and validation results will be cleared\. No directory records have been imported yet\./);
  assert.match(client, /role="dialog"/);
  assert.match(client, /aria-modal="true"/);
  assert.match(client, /aria-labelledby="discard-import-title"/);
  assert.match(client, /aria-describedby="discard-import-description"/);
  assert.match(client, /tabIndex=\{-1\}/);
  assert.match(client, /event\.key === "Escape"/);
  assert.match(client, /aria-label="Cancel discard import"/);
  assert.match(client, /aria-label="Discard import and clear preview"/);
  assert.match(client, /role="status"/);
  assert.match(client, /aria-live="polite"/);
});

test("directory import workflow: confirm discard clears only transient upload and preview state", () => {
  const client = readFileSync(new URL("../components/workspace/DirectoryImportClient.tsx", import.meta.url), "utf8");
  const resetBody = client.match(/function resetTransientImportState[\s\S]*?\n  \}/)?.[0] ?? "";
  assert.match(resetBody, /setPreviewPayload\(null\)/);
  assert.match(resetBody, /setSelectedFilename\(null\)/);
  assert.match(resetBody, /setImportIdentity\(null\)/);
  assert.match(resetBody, /setPendingReplacementFile\(null\)/);
  assert.match(resetBody, /setConfirmOpen\(false\)/);
  assert.match(resetBody, /setError\(null\)/);
  assert.match(resetBody, /setImporterState\(nextState\)/);
  assert.match(resetBody, /resetFileInput\(\)/);
  assert.match(resetBody, /uploadButtonRef\.current\?\.focus\(\)/);
  assert.match(client, /data-preview-token-present=\{importIdentity \? "true" : "false"\}/);
});

test("directory import workflow: discard does not call commit delete or rollback APIs", () => {
  const client = readFileSync(new URL("../components/workspace/DirectoryImportClient.tsx", import.meta.url), "utf8");
  const discardBody = client.match(/function confirmDiscard\(\) \{[\s\S]*?\n  \}/)?.[0] ?? "";
  assert.doesNotMatch(discardBody, /fetch\(/);
  assert.doesNotMatch(discardBody, /commit_workspace_directory_import|\/api\/workspace\/directory\/commit/i);
  assert.doesNotMatch(discardBody, /delete|rollback/i);
  assert.doesNotMatch(client, /\/api\/workspace\/directory\/delete|\/api\/workspace\/directory\/rollback/);
});

test("directory import workflow: selecting a second file prompts before replacing an active preview", () => {
  const client = readFileSync(new URL("../components/workspace/DirectoryImportClient.tsx", import.meta.url), "utf8");
  assert.match(client, /if \(hasUncommittedPreview\) \{/);
  assert.match(client, /setPendingReplacementFile\(file\)/);
  assert.match(client, /setConfirmOpen\(true\)/);
  assert.match(client, /You have an uncommitted directory import\. Discard it before starting another import\./);
  assert.match(client, /window\.setTimeout\(\(\) => void handleFile\(replacement\), 0\)/);
});

test("directory import workflow: successful commit preserves history and offers a clean next import", () => {
  const client = readFileSync(new URL("../components/workspace/DirectoryImportClient.tsx", import.meta.url), "utf8");
  const commitBody = client.match(/async function commitImport\(\) \{[\s\S]*?\n  \}/)?.[0] ?? "";
  assert.match(commitBody, /\/api\/workspace\/directory\/commit/);
  assert.match(commitBody, /setPreviewPayload\(null\)/);
  assert.match(commitBody, /setSelectedFilename\(null\)/);
  assert.match(commitBody, /setImportIdentity\(null\)/);
  assert.match(commitBody, /setImporterState\("committed"\)/);
  assert.match(commitBody, /Import completed successfully/);
  assert.match(commitBody, /await refreshDashboard\(\)/);
  assert.match(client, /function startNewImport\(\) \{\s*resetTransientImportState\("idle", "Ready for a new directory import\."\);/);
  assert.match(client, /Import History/);
});

test("directory import workflow: commit is blocked for errors and duplicates but not warnings alone", () => {
  const client = readFileSync(new URL("../components/workspace/DirectoryImportClient.tsx", import.meta.url), "utf8");
  const service = readFileSync(new URL("../lib/workspace/directoryImport.ts", import.meta.url), "utf8");
  assert.match(client, /preview\.errors\.length > 0 && preview\.duplicates > 0/);
  assert.match(client, /Resolve the validation errors before committing\./);
  assert.match(client, /Resolve the duplicate records before committing\./);
  assert.match(client, /Resolve the duplicate and validation errors before committing\./);
  assert.match(client, /if \(blockingMessage\) \{[\s\S]*?blockedMessageRef\.current\?\.focus\(\{ preventScroll: true \}\)[\s\S]*?return;/);
  assert.match(client, /aria-describedby=\{blockedMessage \? "directory-import-blocked-reason" : undefined\}/);
  assert.match(service, /preview\.errors\.length > 0 \|\| preview\.duplicates > 0/);
  assert.doesNotMatch(client, /warnings\.length > 0[\s\S]*?return;/);
});

test("directory import workflow: preview and committed summaries use accurate terminology", () => {
  const client = readFileSync(new URL("../components/workspace/DirectoryImportClient.tsx", import.meta.url), "utf8");
  assert.match(client, /<Metric label="Ready to Import" value=\{preview\.imported\} \/>/);
  assert.match(client, /<Metric label="Will Be Skipped" value=\{preview\.skipped\} \/>/);
  assert.match(client, /<Metric label="Blocking Issues" value=\{blockingIssueCount\} \/>/);
  assert.match(client, /setLastCommittedCount\(payload\.summary\?\.imported \?\? previewPayload\.preview\.rowsToInsert\.length\)/);
  assert.match(client, /Imported: \{lastCommittedCount\}/);
});

test("directory import workflow: informational panels are passive and do not trigger navigation prompts", () => {
  const client = readFileSync(new URL("../components/workspace/DirectoryImportClient.tsx", import.meta.url), "utf8");
  const issueList = client.match(/function IssueList[\s\S]*$/)?.[0] ?? "";
  assert.match(issueList, /pointer-events-none select-none/);
  assert.doesNotMatch(issueList, /onClick|href|button|tabIndex/);
  assert.match(client, /window\.addEventListener\("beforeunload", onBeforeUnload\)/);
  assert.doesNotMatch(client, /onClick=\{onBeforeUnload\}|onMouseDown=\{onBeforeUnload\}/);
});

test("directory import workflow: duplicate rows are visually identifiable with explanations", () => {
  const client = readFileSync(new URL("../components/workspace/DirectoryImportClient.tsx", import.meta.url), "utf8");
  const importer = readFileSync(new URL("../lib/deploymentLocationsImport.ts", import.meta.url), "utf8");
  assert.match(client, /data-row-status=\{row\.status\}/);
  assert.match(client, /row\.status === "duplicate" \? "bg-amber-50"/);
  assert.match(client, /Skipped duplicate: \{row\.duplicateReason\}/);
  assert.match(importer, /Same \$\{duplicateDetails\.slice/);
  assert.match(importer, /This row will not be imported/);
  assert.doesNotMatch(importer, /Duplicate Name: row/);
  assert.doesNotMatch(importer, /Duplicate Outlet Code \(ID\): row/);
});

test("directory import workflow: blocked reminder is near commit and does not highlight preview card", () => {
  const client = readFileSync(new URL("../components/workspace/DirectoryImportClient.tsx", import.meta.url), "utf8");
  assert.match(client, /ref=\{blockedMessageRef\}/);
  assert.match(client, /role="alert"/);
  assert.match(client, /focus\(\{ preventScroll: true \}\)/);
  assert.doesNotMatch(client, /validationSummaryRef/);
  assert.doesNotMatch(client, /focus:ring-2 focus:ring-orange-500/);
  assert.match(client, /className="space-y-4 rounded-lg border border-slate-200 bg-white p-5"/);
});

test("directory import workflow: blocking issues count includes errors and duplicate rows once", () => {
  const client = readFileSync(new URL("../components/workspace/DirectoryImportClient.tsx", import.meta.url), "utf8");
  const preview = previewDeploymentLocationImport([
    { state: "", outlet_name: "Bad", address: "1 Road", outlet_code: "BAD-1" },
    { state: "Lagos", outlet_name: "Devine Venture'S", address: "1 Road", outlet_code: "236120" },
    { state: "Lagos", outlet_name: "Devine Venture'S", address: "2 Road", outlet_code: "236120" },
  ], [], "retail");
  assert.equal(preview.errors.length, 1);
  assert.equal(preview.duplicates, 1);
  assert.equal(preview.errors.length + preview.duplicates, 2);
  assert.match(client, /const blockingIssueCount = preview \? preview\.errors\.length \+ preview\.duplicates : 0/);
  assert.match(client, /<IssueList title="Blocking Issues" items=\{blockingIssues\(preview\)\}/);
  assert.match(client, /issue\.field === "duplicate"/);
});

test("directory import workflow: only one actionable template download remains", () => {
  const page = readFileSync(new URL("../app/workspace/admin/upload-directory/page.tsx", import.meta.url), "utf8");
  const client = readFileSync(new URL("../components/workspace/DirectoryImportClient.tsx", import.meta.url), "utf8");
  assert.doesNotMatch(page, /href="\/api\/workspace\/directory\/template"/);
  assert.match(client, /href="\/api\/workspace\/directory\/template"/);
  assert.match(client, /aria-label=\{`Download \$\{directoryLabel\} template`\}/);
  assert.match(client, /bg-slate-950/);
  assert.match(client, /text-white/);
  assert.match(client, /focus:ring-2 focus:ring-slate-950 focus:ring-offset-2/);
  assert.match(client, /"Download Template"/);
});
